name: Publish Docker image

on:
  push:
    branches: Code-chef

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: anurag0072/ticket_tracker01:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
